spring.application.name=api-camping
server.port=8083
server.servlet.context-path=/api

spring.cloud.config.import-check.enabled=false
spring.cloud.config.fail-fast=false

spring.datasource.url=jdbc:postgresql://localhost:5432/campconnect_camping
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

cloudinary.cloud-name=dczqefpdb
cloudinary.api-key=496427515753929
cloudinary.api-secret=n-zjAvwxckpv6zxxHyiBHo-q_8k

app.stripe.secret-key=sk_test_51RAZhOPTsghyMozmafa4IwabpoMN1t7VSXBu1PIwLBRorwuAXY1dMH0D7OhzzpJSu1Jt1Z3QBTp2EYOTrGUjhOt600HpdHL2uo
app.stripe.publishable-key=pk_test_51RAZhOPTsghyMozm3oMlw5ZEAUVs7qwd1gfsnyPCMnJsB3CXCF3MxpqcvYYeZGKQZiOCHNALMuqh7olFqsydUetB0085g1Udo0
app.stripe.webhook-secret=whsec_94c8f1f74e5b67b00ebc1641c5cdffa05bbae014f680f9dcc3aa2704eebd890a
app.stripe.currency=usd
app.stripe.frontend-base-url=http://localhost:4200

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=molk.saouabi@gmail.com
spring.mail.password=ydmg gmem gife djgn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.jwt.secret=MyUltraSecureJwtSecretKeyThatIsAtLeast32CharsLong123

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/config